name: _loading
description: Load required parameters for the subsequent jobs

on:
  workflow_call:
    inputs:
      event_name:
        description: Event name
        type: string
        required: true
      pr_ref:
        description: PR head ref
        type: string
        required: false
        default: ""
      pr_repo:
        description: PR head repo full name
        type: string
        required: false
        default: ""
      base_ref:
        description: Base ref
        type: string
        required: false
        default: ""
    outputs:
      build_matrix:
        description: Build matrix
        value: ${{ jobs.loading.outputs.build_matrix }}

jobs:
  loading:
    runs-on: ubuntu-latest
    outputs:
      build_matrix: ${{ steps.loading.outputs.build_matrix }}
    steps:
      - name: Sync codebase
        uses: qualcomm-linux/video-driver/.github/actions/sync@meta-qcom
        with:
          event_name: ${{ inputs.event_name }}
          pr_ref: ${{ inputs.pr_ref }}
          pr_repo: ${{ inputs.pr_repo }}
          base_ref: ${{ inputs.base_ref }}

      - name: Load Parameters
        id: loading
        uses: qualcomm-linux/video-driver/.github/actions/loading@meta-qcom